label scene_1_start:
    # Show jonah
    jonah "{font=fonts/Baskervville-Italic-VariableFont_wght.ttf}Deep breaths, Jonah. You’ve done this several times before, it’s going to be well.{/font}"
    jonah "{font=fonts/Baskervville-Italic-VariableFont_wght.ttf}Just… follow the protocol. Review the manual if you need it, it’s perfectly acceptable.{/font}"
    "TOME OF RESURRECTION"
    "Step 1: Soul Inspection"
    "As a necessary step for employee ressurection, necromancers must perform a psychological evaluation to make sure the spirit is stable and willing to return to the realm of the living."
    jonah "Are there any spirits in the room?"
    # TODO: Add light effects
    jonah "Lyria Silvermoon, are you in my presence? Please, show yourself!"
    show lyria at right with dissolve:
        zoom 0.25
    lyria "Jonah... why are you summoning me? Aren't you going to revive me?"
    jonah "Lyria! Thank Lordran you're well!"
    jonah "I wanted to check the state of your spirit. It's part of the procuedure. You know this."
    lyria "Right... yes."
    jonah "How are you feeling? Are you stable?"
    lyria "Relatively. I feel anchored enough, but I sense I had a terrible death."
    jonah "Yes... I know. I read the report."
    jonah "Can you recount what happened before your expiration?"
    lyria "It was bloody..."
    lyria "It was bloody... the greatest behemoth I've ever seen. I watched him rip apart every member of my unit, one by one."
    lyria "I was the last."
    jonah "I'm so sorry, dear. But you're strong. I'm glad to see your spirit remains firm after an experience like that."
    lyria "Yeah..."
    jonah "What about you? How are you feeling at the moment?"
    lyria "I feel..."
    lyria "I feel... nothing."
    jonah "..."
    jonah "...Are you sure? Can you describe any thoughts? Sensations?"
    lyria "I feel... cold. Seeing my team fall in front of me..."
    lyria "I feel... cold. Seeing my team fall in front of me... brought me great pain, but after my death..."
    lyria "I'm completely numb."
    jonah "Oh, Lyria... all is well. You will trudge along this path. I'm here with you."
    lyria "..."
    jonah "Remember how you wanted to visit Novaria for our next holiday? Are you still looking forward to that?"
    lyria "Yes!"
    jonah "Good. Hang on to that feeling. You're in good hands. I brought you back before, and I'll do it again. I swear on Lordran."
    lyria "Thank you."
    lyria "I love you, Jonah."
    jonah "I love you, Lyria."
    jonah "With that said, are you willing to return to the realm of the living?"
    lyria "I consent."
    jonah "Good. Any last words before your reanimation?"
    lyria "How..."
    lyria "How... what's the state of my body?"
    jonah "I haven't looked yet. Based on the reports, it wasn't in a pristine state."
    lyria "..."
    jonah "Once again: Don't worry! You're in good hands. I'll revive you in sun or rain, even if I have to rip you out of the hands of Myrra herself."
    lyria "Thank you."
    lyria "Good luck, Jonah."
    hide lyria
    jonah "{font=fonts/Baskervville-Italic-VariableFont_wght.ttf}Note: Spirit is anchored. Ressurection consent: approved{/font}"
    jonah "I'll uncover the body."
    "he uncovered the body."
    jonah "{font=fonts/Baskervville-Italic-VariableFont_wght.ttf}Just as the report described. Focus Jonah, her life depends on it.{/font}"
    "Step 2. Body reassembly"
    "Stitch together any dismembered body parts. Connect electric diodes to the head's temples. Once finished, flip the power switch on to reanimate the body."
    jonah "{font=fonts/Baskervville-Italic-VariableFont_wght.ttf}Here goes...{/font}"
    jonah "Rise! Lyria, rise!"
    # TODO: Electric sound effects, flash of light, change of music
    jonah "Lyria! Are you alive? Please, speak!"
    lyria "Jonah... I..."
    lyria "..."
    jonah "Lyria? Are you well? Say something!"
    lyria "Shed your blood, meager mortal! Blood for Haxos! Blood for the Neatherlord!"
    "In case the body displays signs of possession, such as unusual speech, immediately turn the power off."
    # TODO: Power off sound
    jonah "{font=fonts/Baskervville-Italic-VariableFont_wght.ttf}This is strange... is her body possessed? Beheamoths aren't nether creatures, it's impossible one of them could corrupt her body.{/font}"
    jonah "{font=fonts/Baskervville-Italic-VariableFont_wght.ttf}This corruption must’ve been dormant for a while. I must replace the corrupt body parts until the entire body is pure!{/font}"
    "In case of possession, one or more body parts must be corrupt. Replace whichever body parts are corrupt and which are pure."
    # Power on sound
    jonah "Lyria? Are you yourself again?"
    lyria "..."
    lyria "Ah..."
    lyria "AAAAAAAAAAAAAAAAAAAAAAAHHHH!"
    jonah "Lyria! Control yourself!"
    lyria "Make it stop! MAKE IT STOP! The pain is unbearable! I shouldn’t have come back! PLEASE, MAKE IT STOP!!!"
    # Power off sound
    jonah "{font=fonts/Baskervville-Italic-VariableFont_wght.ttf}How is this possible? An incompatible reaction? Lyria has never suffered one before!{/font}"
    jonah "{font=fonts/Baskervville-Italic-VariableFont_wght.ttf}I must perform another evacuation immediately!{/font}"
    jonah "Are there any spirits in this room?"
    # rune light effect
    jonah "Lyria Silvermoon, please show yourself!"
    show lyria with dissolve
    lyria "What happened? That felt awful!"
    jonah "Don't worry, you just had an incompatible reaction. It happens when the body and the mind aren't adequately in tune."
    jonah "I'm not sure why it happened..."
    jonah "I'm not sure why it happened... maybe there was a latent curse undetected or some malfunction in the brain?"
    jonah "Gahhhh! I'm so stupid! How did I not see it in the horizon?"
    lyria "All is well, Jonah. Don't punish yourself for it."
    jonah "I'm afraid to announce your ressurection will have to wait. I must perform further diagnostics."
    jonah "But, before I do... Lyria, where you truly willing to come back to life?"
    lyria "..."
    lyria "I have to confess..."
    lyria "I have to confess... recently, I've had some reticence in my ressurections."
    jonah "What? Why?"
    lyria "Times are changing, Jonah... I'm not the same. Now, I feel like a cog in the Dungeon Industries machine."
    lyria "Why should I come back to life if I'll just perish once again? Every time, I feel my purpose fade more and more..."
    lyria "What is my purpose anymore? Senselessly keep raining arrows upon monsters until my spirit finally breaks?"
    jonah "Lyria, please... don't speak like that... you have so much to live for! You're only 121! That's mid 20's in elf years!"
    lyria "I know..."
    jonah "Think about your loved ones! Think about me. Are you ready to leave behind everything and everyone in your life?"
    lyria "..."
    lyria "I'm not sure... I feel distressed."
    jonah "If you're hurting, we can adjourn your evaluation. Just... please. Think it over. I'm not ready to see you go just yet."
    lyria "..."
    lyria "Very well. Farewell, Jonah."
    hide lyria
    jonah "Goodbye."
    jonah "{font=fonts/Baskervville-Italic-VariableFont_wght.ttf}I'll take some fluid samples and study them. There must be some reason behind that reaction.{/font}"
    # TODO: Fade to black, then back in again